---
- name: Create service user
  user:
    name: "{{scmmanager_user}}"
    state: present
    system: yes

- name: Download and uncompress server tarball
  unarchive:
    src: "https://maven.scm-manager.org/nexus/content/repositories/releases/sonia/scm//scm-server/{{scmmanager_version}}/scm-server-{{scmmanager_version}}-app.tar.gz"
    dest: /opt
    remote_src: yes
    validate_certs: no
    creates: /opt/scm-server
    owner: "{{scmmanager_user}}"
    group: "{{scmmanager_user}}"
    mode: 0755
  
- name: Copy service template
  template:
    src: scmmanager.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644

- name: Enable systemd service
  systemd:
    name: scmmanager
    enabled: yes
    daemon_reload: yes
  notify: Restart scmmanager service
