---
- include_tasks: "{{ansible_os_family}}.yml"

- name: Copy service template
  template:
    src: scmmanager.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644

- name: Enable systemd service
  systemd:
    name: scmmanager
    enabled: yes
    daemon_reload: yes

