---
- name: Add scmmanager yum repo
  copy:
    src: SCM-Manager.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 0644

- name: Install required packages
  yum:
    name: 
      - scm-server
    state: present
    disable_gpg_check: yes
    